# Generated by Codex on 2026-06-19

from django.db import migrations, models


STATE_NAME_TRANSLATIONS = {
    "Backlog": "Бэклог",
    "Todo": "К выполнению",
    "In Progress": "В работе",
    "Done": "Готово",
    "Cancelled": "Отменено",
    "Triage": "Разбор",
}


def set_russian_defaults(apps, schema_editor):
    Profile = apps.get_model("db", "Profile")
    State = apps.get_model("db", "State")

    Profile.objects.filter(language__in=["", "en"]).update(language="ru")

    for old_name, new_name in STATE_NAME_TRANSLATIONS.items():
        State.objects.filter(name=old_name).update(name=new_name)


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0121_alter_estimate_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="language",
            field=models.CharField(default="ru", max_length=255),
        ),
        migrations.AlterField(
            model_name="state",
            name="group",
            field=models.CharField(
                choices=[
                    ("backlog", "Бэклог"),
                    ("unstarted", "К выполнению"),
                    ("started", "В работе"),
                    ("completed", "Готово"),
                    ("cancelled", "Отменено"),
                    ("triage", "Разбор"),
                ],
                default="backlog",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Бэклог"),
                    ("planned", "Запланировано"),
                    ("in-progress", "В работе"),
                    ("paused", "Приостановлено"),
                    ("completed", "Готово"),
                    ("cancelled", "Отменено"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_russian_defaults, migrations.RunPython.noop),
    ]
